---

bookstack_name: bookstack
bookstack_image: linuxserver/bookstack
bookstack_ports:
  - 80:80
bookstack_config_directory: "{{ common_directory_config }}/bookstack"
bookstack_volumes:
  - "{{ bookstack_config_directory}}:/config"
bookstack_environment_variables:
  PUID: "{{ common_user_id }}"
  PGID: "{{ common_group_id }}"
  DB_HOST: "{{ mariadb_name }}"
  DB_USER: "{{ mariadb_environment_variables.MYSQL_USER }}"
  DB_PASS: "{{ mariadb_environment_variables.MYSQL_PASSWORD }}"
  DB_DATABASE: "{{ mariadb_environment_variables.MYSQL_DATABASE }}"

bookstack_docker_additional_options:
  restart_policy: unless-stopped
  networks: "{{ docker_networks }}"

bookstack_env_options:
  - WKHTMLTOPDF=/usr/bin/wkhtmltopdf
  - DRAWIO=true
  - APP_TIMEZONE=Australia/Sydney
